# Pandas

In [1]:
# Pandas is developed based on numpy
# Pandas is better to analze and manipulate the dataset..

## How to generate data using Pandas

In [2]:
import pandas as pd

In [3]:
## Series(Sequence data)
# pd.Series(sequence data)

In [6]:
s1 = pd.Series([10,20,30,40,50])

In [ ]:
#index, value

In [5]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [9]:
s2 = pd.Series(['a','b','c',1,2,3]) #numpy array와는 다르게 mix data type사용 가능

In [10]:
s2.index

RangeIndex(start=0, stop=6, step=1)

In [11]:
s2.values

array(['a', 'b', 'c', 1, 2, 3], dtype=object)

### missing vlaue

In [12]:
import numpy as np

In [13]:
s3=pd.Series([np.nan,10,30]) #nan -> missing value

In [14]:
s3

0     NaN
1    10.0
2    30.0
dtype: float64

## DataFrame(2-dimensional data)

In [16]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [18]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [20]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [21]:
 import numpy as np

In [23]:
# ndarray
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
type(np.arange(0,9).reshape(3,3))

numpy.ndarray

In [24]:
# pandas
pd.DataFrame(np.arange(0,9).reshape(3,3))

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [27]:
type(pd.DataFrame(np.arange(0,9).reshape(3,3)))

pandas.core.frame.DataFrame

In [28]:
# you can change the name of index and columns 

In [29]:
pd.DataFrame(np.arange(0,9).reshape(3,3), index=['a','b','c'])

0  1  2
a  0  1  2
b  3  4  5
c  6  7  8

In [30]:
pd.DataFrame(np.arange(0,9).reshape(3,3), index=['a','b','c'], columns=['x','y','z'])

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8

In [ ]:
# lust, ndarray -> Pandas 
# dictionary -> Pandas 

In [ ]:
# key -> columns! 
# value -> value!

In [35]:
table = {'year':[2015,2016,2017,2018],
        'sales':[200,250,450,300],
        }

In [37]:
table

{'year': [2015, 2016, 2017, 2018], 'sales': [200, 250, 450, 300]}

In [38]:
pd.DataFrame(table)

year  sales
0  2015    200
1  2016    250
2  2017    450
3  2018    300

### operation

In [39]:
s1=pd.Series([1,2,3,4,5])

In [40]:
s2=pd.Series([10,20,30,40,50])

In [41]:
s1+s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [42]:
s1-s2

0    -9
1   -18
2   -27
3   -36
4   -45
dtype: int64

In [43]:
s1*s2

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [44]:
s1/s2

0    0.1
1    0.1
2    0.1
3    0.1
4    0.1
dtype: float64

In [51]:
table_2={"A":[1,2,3],
        "B":[10,20,30],
        "C":[100,200,300]}

In [55]:
df2=pd.DataFrame(table_2)

In [49]:
table_3={"A":[6,7],
        "B":[60,70],
        "C":[600,700]}

In [56]:
df3=pd.DataFrame(table_3)

In [57]:
df2.shape

(3, 3)

In [58]:
df3.shape

(2, 3)

In [59]:
df2+df3

A     B      C
0  7.0  70.0  700.0
1  9.0  90.0  900.0
2  NaN   NaN    NaN

In [60]:
df2-df3

A     B      C
0 -5.0 -50.0 -500.0
1 -5.0 -50.0 -500.0
2  NaN   NaN    NaN

In [61]:
df2*df3

A       B         C
0   6.0   600.0   60000.0
1  14.0  1400.0  140000.0
2   NaN     NaN       NaN

In [62]:
df2/df3

A         B         C
0  0.166667  0.166667  0.166667
1  0.285714  0.285714  0.285714
2       NaN       NaN       NaN

### descriptive statistic

In [63]:
table_4={'Spring':[256,264,215,312],
        'Summer':[770,567,599,387],
        'Fall':[363,231,293,247],
        'Winter':[139,59,76,109]}

In [66]:
df5=pd.DataFrame(table_4,index=['2012','2013','2014','2015'], columns=['Spring','Summer','Fall','Winter'])

In [68]:
df5

Spring  Summer  Fall  Winter
2012     256     770   363     139
2013     264     567   231      59
2014     215     599   293      76
2015     312     387   247     109

In [67]:
# sum for each column
df5.sum()

Spring    1047
Summer    2323
Fall      1134
Winter     383
dtype: int64

In [69]:
# sum for each index
df5.sum(axis=1)

2012    1528
2013    1121
2014    1183
2015    1055
dtype: int64

In [71]:
# mean for each column
df5.mean()

Spring    261.75
Summer    580.75
Fall      283.50
Winter     95.75
dtype: float64

In [72]:
# mean for each index
df5.mean(axis=1)

2012    382.00
2013    280.25
2014    295.75
2015    263.75
dtype: float64

In [73]:
# Standard deviation for each column
df5.std()

Spring     39.785885
Summer    156.925407
Fall       59.157981
Winter     35.528158
dtype: float64

In [74]:
# min for each column
df5.min()

Spring    215
Summer    387
Fall      231
Winter     59
dtype: int64

In [75]:
# max for each column
df5.max()

Spring    312
Summer    770
Fall      363
Winter    139
dtype: int64

In [76]:
# descriptive statistics
df5.describe()

Spring      Summer        Fall      Winter
count    4.000000    4.000000    4.000000    4.000000
mean   261.750000  580.750000  283.500000   95.750000
std     39.785885  156.925407   59.157981   35.528158
min    215.000000  387.000000  231.000000   59.000000
25%    245.750000  522.000000  243.000000   71.750000
50%    260.000000  583.000000  270.000000   92.500000
75%    276.000000  641.750000  310.500000  116.500000
max    312.000000  770.000000  363.000000  139.000000

In [77]:
type(df5.describe())

pandas.core.frame.DataFrame

In [78]:
df5.describe().shape

(8, 4)

In [ ]:
20 team! 
1) Project : Github에서 코드 다운받기.
    - Interpretation of a preexisting code(해석하기)
    - Modify the code

* 다음주에 summarize the tasks in a documnet, is going to upload it
github.com/eduardosm7/knn-python/blob/master/Classification/survival-knn.ipynb