In [3]:
import numpy as np

## How to create numpy arrays

In [4]:
### sequence data

In [5]:
np.array([0.0,1.2,3.4,5.6] ) ##array(type the data ex. list, tuple, dic) 

array([0. , 1.2, 3.4, 5.6])

In [6]:
obj=np.array([0.0,1.2,3.4,5.6])

In [7]:
#type of the elements in obj is int

In [8]:
obj.dtype #dtype is a property of obj

dtype('float64')

In [9]:
type(obj) #ndarray : N dimensional Array, support computation multi-dimensional matrix, array 

numpy.ndarray

In [10]:
### matrix

In [11]:
np.array([[1,2,3], [4,5,6], [7,8,9]]) #3-by-3 array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange: similar with rage

In [14]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# np.arange(number of value) ex) np.arrage(3) = [0,1,2]
# np.arange(start, end)
# np.arange(start, end, step_size)

In [15]:
np.arange(1,6,2)

array([1, 3, 5])

In [17]:
#reshape the array
np.arange(1,6,2).reshape(3,1)

array([[1],
       [3],
       [5]])

In [20]:
#to check the dim of the array
np.arange(1,6,2).shape

(3,)

In [22]:
np.arange(1,6,2).reshape(3,1).shape

(3, 1)

In [24]:
np.arange(10).reshape(2,5).shape

(2, 5)

In [27]:
np.arange(10).reshape(5,2).shape

(5, 2)

### What if we want to generate an array with real number?

In [28]:
# np.linspace(starting nubmer, ending num, number of elements in relarray)

In [29]:
np.linspace(0, np.pi, 100)

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [30]:
np.linspace(0, np.pi, 100).shape

(100,)

In [31]:
np.linspace(0, np.pi, 100).reshape(10,10)

array([[0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
        0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933],
       [0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
        0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192],
       [0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
        0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451],
       [0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
        1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711],
       [1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
        1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ],
       [1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
        1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229],
       [1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
        2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488],
       [2.22132814, 2.2530614 , 2.2847946

In [ ]:
 # numpy! <- we can easily use linear algebra
    

### zero matrix

In [33]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### one matrix

In [34]:
np.ones(10).reshape(10,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

### identify matrix

In [35]:
np.eye(5) # num of diagonal elements in the identtity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## changing the type of data: convert the type of the ndarray data

In [37]:
string=np.array(['1.5','0.62','2','3.14']) # all the elements of ndrray are string.

In [41]:
# how can we convert the string into float?
number=string.astype(float)

In [39]:
## object_name.astype(data_type) -> you can change the type of data

In [42]:
number.dtype

dtype('float64')

In [43]:
string2=np.array(['1','0','2','3']) # all the elements of ndrray are string.

In [45]:
integer=string2.astype(int)

In [46]:
integer.dtype

dtype('int32')

- create ndarray in numpy
- reshape ndarray
- zero vecto, one vector, and an identity matrix

## random number generation in numpy

In [1]:
## When you learn ML algorithm or regression methods, the best way is a simulation.

In [2]:
## you need to generate random numbers..

In [3]:
# rand : generate real number whose range is (0,1)
# randint : generate integer..

In [4]:
import numpy as np

#### rand()

In [7]:
np.random.rand() # if I do not put anything in the parenthesis, python generate a single number..

0.5466752452230803

In [8]:
# np.random.rand([decide the dimension of random number])

In [9]:
np.random.rand(3) # generate 1-by-3 vector

array([0.24098179, 0.88165988, 0.47403129])

In [10]:
np.random.rand(3).shape

(3,)

In [11]:
np.random.rand(3,2) # 3-by-2 matrix

array([[0.12713413, 0.18527482],
       [0.09318205, 0.70786946],
       [0.29081584, 0.86448871]])

In [12]:
np.random.rand(3,2,3) # 3-by-2-by-3

array([[[0.1345427 , 0.78144329, 0.66818575],
        [0.81671657, 0.60024991, 0.91761261]],

       [[0.94012616, 0.34625554, 0.35929277],
        [0.91760714, 0.53417071, 0.94417412]],

       [[0.6255292 , 0.85411332, 0.20302355],
        [0.95250777, 0.52107629, 0.32817204]]])

#### randint()

In [13]:
## np.random.randint({1ower, upper}, size) lowerbound : included, upperbound : not include

In [15]:
np.random.randint(0, 10, size=(3,4)) # 3-by-4 matrix

array([[7, 5, 8, 6],
       [6, 3, 1, 3],
       [3, 4, 8, 6]])

In [16]:
np.random.randint(0, 10) # single number

2

### operation/ math, algebra

In [21]:
# summation
arr1=np.array([0,1,3])
arr2=np.array([2,4,5])

In [22]:
arr1+arr2 #elementwise sumation

array([2, 5, 8])

In [24]:
arr1-arr2 # elementwise subtraction

array([-2, -3, -2])

In [25]:
arr1*arr2 # elementwise multiplication

array([ 0,  4, 15])

In [26]:
arr1/arr2 # elementwise division

array([0.  , 0.25, 0.6 ])

In [27]:
arr1*2 # multiply a scalar

array([0, 2, 6])

In [28]:
arr1**2 # power of elements

array([0, 1, 9], dtype=int32)

In [29]:
# logical operation
arr1>2

array([False, False,  True])

### descriptive statistic of the elements

In [30]:
arr1.mean()

1.3333333333333333

In [31]:
arr1.sum()

4

In [32]:
arr1.std()

1.247219128924647

In [34]:
[arr1.min(), arr1.max()]

[0, 3]

### computation of matrix

1. dot product
2. transpose
3. inverse matrix
4. determinant
5. etc..

In [35]:
# dot product

In [36]:
mat1=np.arange(4).reshape(2,2)

In [37]:
mat1

array([[0, 1],
       [2, 3]])

In [40]:
mat2=np.arange(5,9).reshape(2,2)

In [41]:
mat2

array([[5, 6],
       [7, 8]])

In [42]:
mat1.dot(mat2) # A.dot(B) = np.dot(A,B)

array([[ 7,  8],
       [31, 36]])

In [43]:
np.dot(mat1, mat2)

array([[ 7,  8],
       [31, 36]])

In [44]:
# transpose

In [45]:
np.transpose(mat1)

array([[0, 2],
       [1, 3]])

In [46]:
# inverse -> np.linalg.inv()

In [49]:
np.linalg.inv(mat1)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [50]:
# determinant

In [51]:
np.linalg.det(mat1)

-2.0

 ### index and slicing of ndarray 

In [60]:
# idexing sequence

In [53]:
a1=np.arange(10)

In [54]:
a1[0]

0

In [55]:
a1[4]

4

In [56]:
a1[5]=70 # updating an element

In [58]:
a1

array([ 0,  1,  2,  3,  4, 70,  6,  7,  8,  9])

In [59]:
a1[[0,3,5]] # array_name[[loc1, loc2, loc3...]]

array([ 0,  3, 70])

In [61]:
# index of matrix

In [63]:
a2=a1.reshape(5,2)

In [64]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4, 70],
       [ 6,  7],
       [ 8,  9]])

In [65]:
# a2[row_num, column_num]

In [66]:
a2[2,1]

70

In [68]:
a2[2] #print the 3rd row

array([ 4, 70])

In [69]:
# update a number
a2[2,1]=80

In [70]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4, 80],
       [ 6,  7],
       [ 8,  9]])

In [71]:
a2[0]=np.array([1,3])

In [72]:
a2

array([[ 1,  3],
       [ 2,  3],
       [ 4, 80],
       [ 6,  7],
       [ 8,  9]])

In [73]:
# you can print multiple number in a matirx.
a2[[1,4],[0,1]] # array_name[[row_numbers],[column_names]]

array([2, 9])

### indexing using a condition

In [74]:
a1>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
#print only the number that satisisfies the condition
a1[a1>3]

array([ 4, 80,  6,  7,  8,  9])

### slicing 

In [77]:
# slicing a sequence
seq1=np.arange(20)

In [78]:
seq1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
seq1[4:11] # array_name[starting location : ending location]

array([ 4,  5,  6,  7,  8,  9, 10])

In [81]:
# slicing a matrix

In [82]:
mat3=seq1.reshape(5,4)

In [83]:
mat3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
# mat3[row_name, column_name]

In [85]:
mat3[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [86]:
mat3[2:,1:]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])